### ISSUE TITLE
影响项目内的Icon图标

### ISSUE THREAD

**Issue by hqzh** [jindada/tree-transfer#4]
https://codepen.io/hqzh/pen/byZZeN
我看了下，是新版的antd的图标没有用伪类：before，但是组件内的不应该影响全局

**Comment by jindada** [comment]
组件内的css都在`.lucio-tree-transfer`下，能发下是那个样式影响到你了吗

**Comment by hqzh** [comment]
![1](https://user-images.githubusercontent.com/26128706/58923280-95746c00-8771-11e9-9ce2-6101d0d69ccd.png)
![2](https://user-images.githubusercontent.com/26128706/58923298-a7560f00-8771-11e9-9dcb-8a720a563c0b.png)

**Comment by hqzh** [comment]
https://codepen.io/hqzh/pen/byZZeN 这个例子你可以去除引入你的组件和不引入你的组件情况，你看icon多了个伪类的渲染

**Comment by jindada** [comment]
因为antd的样式引起的bug， 后续会把peerDependencies作为外部依赖，而不是dependencies

**Comment by hqzh** [comment]
能否升到最新现在，或者我来升，你合并下

**Comment by hqzh** [comment]
后续你没空改peerDependencies的话我可以来改

**Comment by hqzh** [comment]
@jindada 麻烦npm更新一下版本啊

**Comment by jindada** [comment]
已经更新了 后续欢迎pr

**Comment by hqzh** [comment]
@jindada 现在npm上下来的是空包
