### ISSUE TITLE
相同key的边界处理

### ISSUE THREAD

**Issue by hqzh** [jindada/tree-transfer#9]
![微信截图_20190611085623](https://user-images.githubusercontent.com/26128706/59236029-e7603a80-8c26-11e9-9aba-31b24b85cc1f.png)
我左侧联系人可能同时在不同的组，添加到右侧新组前做个去重判断，如果是相同key则去重只渲染一个

**Comment by jindada** [comment]
在 onChange 中自己去重判断

**Comment by hqzh** [comment]
@jindada 回调里面已经去重了，但是视图还是未变

**Comment by hqzh** [comment]
https://codepen.io/hqzh/pen/gNOwMj?&editable=true&editors=001自带的有这个功能的视图
